### ISSUE TITLE
建议使用 HTTPS CDN

### ISSUE THREAD

**Issue by xuqingfeng** [andylei18/vue-shopping#2]
![image](https://cloud.githubusercontent.com/assets/3715820/15708793/50618184-2833-11e6-96c9-58ebf5e3ed10.png)

HTTPS Everywhere 用户打不开 😂

**Comment by andylei18** [comment]
里面只有一套流程是vue构建的有个a标签跳转的页面是 蘑菇街的。实验性的demo项目不能拿做生产环境运作。。。我的问题。。谢谢你提的宝贵意见
