### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by Lanceloft** [andylei18/vue-shopping#5]
lanceloft@Zatanna:~/code/vue-shopping$ npm run dev

> vue-shopping@1.0.0 dev /home/lanceloft/code/vue-shopping
> node build/dev-server.js

Listening at http://localhost:8888

webpack built 147025876c925006ef74 in 4612ms
Hash: 147025876c925006ef74
Version: webpack 1.13.1
Time: 4612ms
                                             Asset     Size  Chunks       Chunk Names
                                            3.3.js   138 kB       3  
                          src/img/logo.d2f7160.png  44.3 kB  
                    src/fonts/iconfont.51cb24e.ttf    15 kB  
                   src/fonts/iconfont.3af1ed3.woff  10.4 kB  
                      src/img/iconfont.b35431e.svg  22.6 kB  
src/img/top_banner_image_markets_goods.23a3687.jpg   118 kB  
                                            0.0.js   318 kB       0  
                                            app.js   1.6 MB       1       app
                                            2.2.js   205 kB       2  
                    src/fonts/iconfont.9d9001d.eot  15.2 kB  
                                            4.4.js   240 kB       4  
                                            5.5.js   156 kB       5  
                                            6.6.js   257 kB       6  
                                            7.7.js   155 kB       7  
                                            8.8.js  59.5 kB       8  
                                            9.9.js    42 kB       9  
                                          10.10.js  34.9 kB      10  
                                          11.11.js  1.33 kB      11       

ERROR in ./~/.npminstall/babel-loader/6.2.4/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=script&index=0!./src/views/goods/catedetail.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../node_modules/vue-swipe/lib/vue-swipe.css in /home/lanceloft/code/vue-shopping/src/views/goods
 @ ./~/.npminstall/babel-loader/6.2.4/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=script&index=0!./src/views/goods/catedetail.vue 7:0-60

ERROR in ./~/.npminstall/vue-toast-mobile/0.0.6/vue-toast-mobile/lib/index.js
Module not found: Error: Cannot resolve module 'Vue' in /home/lanceloft/code/vue-shopping/node_modules/.npminstall/vue-toast-mobile/0.0.6/vue-toast-mobile/lib
 @ ./~/.npminstall/vue-toast-mobile/0.0.6/vue-toast-mobile/lib/index.js 1:82-96

ERROR in ./~/.npminstall/babel-loader/6.2.4/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=script&index=0!./src/views/timelimit/head.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../node_modules/vue-swipe/lib/vue-swipe.css in /home/lanceloft/code/vue-shopping/src/views/timelimit
 @ ./~/.npminstall/babel-loader/6.2.4/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=script&index=0!./src/views/timelimit/head.vue 7:0-60

ERROR in ./src/views/goods/swipe.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../node_modules/vue-swipe/lib/vue-swipe.css in /home/lanceloft/code/vue-shopping/src/views/goods
 @ ./src/views/goods/swipe.vue 2:0-176
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  22.7 kB       0  
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
webpack building...
webpack built 147025876c925006ef74 in 74ms
Hash: 147025876c925006ef74
Version: webpack 1.13.1
Time: 74ms
                                             Asset     Size  Chunks       Chunk Names
                                            3.3.js   138 kB       3  
                          src/img/logo.d2f7160.png  44.3 kB  
                    src/fonts/iconfont.51cb24e.ttf    15 kB  
                   src/fonts/iconfont.3af1ed3.woff  10.4 kB  
                      src/img/iconfont.b35431e.svg  22.6 kB  
src/img/top_banner_image_markets_goods.23a3687.jpg   118 kB  
                                            0.0.js   318 kB       0  
                                            app.js   1.6 MB       1       app
                                            2.2.js   205 kB       2  
                    src/fonts/iconfont.9d9001d.eot  15.2 kB  
                                            4.4.js   240 kB       4  
                                            5.5.js   156 kB       5  
                                            6.6.js   257 kB       6  
                                            7.7.js   155 kB       7  
                                            8.8.js  59.5 kB       8  
                                            9.9.js    42 kB       9  
                                          10.10.js  34.9 kB      10  
                                          11.11.js  1.33 kB      11       

ERROR in ./~/.npminstall/babel-loader/6.2.4/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=script&index=0!./src/views/goods/catedetail.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../node_modules/vue-swipe/lib/vue-swipe.css in /home/lanceloft/code/vue-shopping/src/views/goods
 @ ./~/.npminstall/babel-loader/6.2.4/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=script&index=0!./src/views/goods/catedetail.vue 7:0-60

ERROR in ./~/.npminstall/babel-loader/6.2.4/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=script&index=0!./src/views/timelimit/head.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../node_modules/vue-swipe/lib/vue-swipe.css in /home/lanceloft/code/vue-shopping/src/views/timelimit
 @ ./~/.npminstall/babel-loader/6.2.4/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/.npminstall/vue-loader/8.5.3/vue-loader/lib/selector.js?type=script&index=0!./src/views/timelimit/head.vue 7:0-60

ERROR in ./src/views/goods/swipe.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../node_modules/vue-swipe/lib/vue-swipe.css in /home/lanceloft/code/vue-shopping/src/views/goods
 @ ./src/views/goods/swipe.vue 2:0-176

ERROR in ./~/.npminstall/vue-toast-mobile/0.0.6/vue-toast-mobile/lib/index.js
Module not found: Error: Cannot resolve module 'Vue' in /home/lanceloft/code/vue-shopping/node_modules/.npminstall/vue-toast-mobile/0.0.6/vue-toast-mobile/lib
 @ ./~/.npminstall/vue-toast-mobile/0.0.6/vue-toast-mobile/lib/index.js 1:82-96

**Comment by ningkaikok** [comment]
swipe.css 路径引用错误。修改为 import '../../../node_modules/vue-swipe/dist/vue-swipe.css'

**Comment by william-xue** [comment]
改了还是报错，跑不通

**Comment by william-xue** [comment]
解决了，遇到问题问我 15895929981
